version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo "Installing Terraform..."
      - wget https://releases.hashicorp.com/terraform/1.0.11/terraform_1.0.11_linux_amd64.zip
      - mkdir -p /tmp/terraform
      - unzip -o terraform_1.0.11_linux_amd64.zip -d /tmp/terraform
      - mv /tmp/terraform/terraform /usr/local/bin/
  pre_build:
    commands:
      - echo "Initializing Terraform..."
      - echo "Current directory before cd terraform in pre_build"
      - pwd
      - cd terraform
      - echo "Current directory after cd terraform in pre_build"
      - pwd
      - terraform init
  build:
    commands:
      - echo "Running Terraform Plan..."
      - echo "Current directory:"
      - pwd
      - terraform destroy -auto-approve
  post_build:
    commands:
      - echo "Terraform Destroy Completed."
