version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x 
    commands:
      - echo Installing Terraform...
      - wget https://releases.hashicorp.com/terraform/1.0.11/terraform_1.0.11_linux_amd64.zip
      - rm -rf terraform
      - unzip -o terraform_1.0.11_linux_amd64.zip
      - mv terraform /usr/local/bin/
  pre_build:
    commands:
      - echo Initializing Terraform...
      - terraform init
  build:
    commands:
      - echo Running Terraform Plan...
      - terraform plan -out=tfplan
  # post_build:
  #   commands:
  #     - echo Applying Terraform Plan...
  #     - terraform apply -auto-approve tfplan
