version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo "Installing Terraform..."
      - wget https://releases.hashicorp.com/terraform/1.0.11/terraform_1.0.11_linux_amd64.zip
      - mkdir -p /tmp/terraform
      - unzip -o terraform_1.0.11_linux_amd64.zip -d /tmp/terraform
      - mv /tmp/terraform/terraform /usr/local/bin/
      - echo Installing Python dependencies...
      - pip install requests python-dotenv
      - apt-get update && apt-get install -y jq
  pre_build:
    commands:
      - echo "Initializing Terraform..."
      - echo "Current directory before cd terraform in pre_build"
      - pwd
      - cd terraform
      - echo "Current directory after cd terraform in pre_build"
      - pwd
      - terraform init
  build:
    commands:
      - echo "Running Terraform Plan..."
      - echo "Current directory:"
      - pwd
      - terraform plan -out=tfplan
      - echo Saving plan log...
      - terraform show -json tfplan > ../deployment_log.txt
  post_build:
    commands:
      - echo "Applying Terraform Plan..."
      - echo "Current directory:"
      - pwd
      - terraform apply -auto-approve tfplan
      - cd ..
      - echo "Fetching OpenAI API key from Secrets Manager"
      - export OPENAI_API_KEY=$(aws secretsmanager get-secret-value --secret-id OPENAI_API_KEY --query 'SecretString' --output text --region us-east-1 | jq -r '.OPENAI_API_KEY')
      - echo "Generating Documentation..."
      - python scripts/generate_docs.py
artifacts:
  files:
    - deployment_documentation.md
